version: 'build-{build}'

image: Visual Studio 2019

environment:
  EMAIL:
    secure: no0uCdrnaWY/44Nfx6Tg+zE71d59XA/0nnJT9LznqtQ=
  ACCESS_TOKEN:
    secure: JIG9V7Fvjdpl1FvBGSTbv5s29nbAL3RcHiHgSaNC7WwoO2jUOBviIPHvQz2TcI/v

install:
  - ps: choco install docfx -y

build_script:
- ps: dotnet restore .\src\Disqord.sln | Out-Host
- ps: dotnet build .\src\Disqord.sln -c "Release" --no-restore | Out-Host

after_build:
- ps: >-
    $HasRepoTag = $Env:APPVEYOR_REPO_TAG -eq "true"

    $BuildNumber = ([int] $Env:APPVEYOR_BUILD_NUMBER).ToString("00000")

    $VersionSuffix = If ($HasRepoTag) {$BuildNumber} Else {"nightly-$BuildNumber"}

    if ($HasRepoTag)
    {
        dotnet pack .\src\Disqord.sln -c Release -o .\artifacts --no-restore --no-build | Out-Host
    }
    else
    {
        dotnet pack .\src\Disqord.sln -c Release -o .\artifacts --no-restore --no-build --version-suffix="$VersionSuffix" | Out-Host
    }

    docfx docs/docfx.json | Out-Host

after_deploy:
  - ps: $Directory = If ($HasRepoTag) {"gh-pages\\stable\\"} Else {"gh-pages\\nightly\\"}
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($Env:ACCESS_TOKEN):x-oauth-basic@github.com`n"
  - ps: git config --global user.email $Env:EMAIL
  - git config --global user.name "Quahu"
  - git clone -q --branch=gh-pages https://github.com/Quahu/Disqord.git gh-pages
  - ps: If (-Not (Test-Path $Directory)) {mkdir $Directory}
  - ps: Remove-Item "$Directory*" -Recurse
  - ps: Copy-Item ".\docs\_site\*" -Destination $Directory -Force -Recurse
  - ps: cd $Directory
  - git add .
  - ps: git commit --allow-empty -m "Build successful. Updated $Directory to $VersionSuffix."
  - git push origin gh-pages

nuget:
  disable_publish_on_pr: true

pull_requests:
  do_not_increment_build_number: true

test: off

artifacts:
- path: .\artifacts\*.nupkg
  name: NuGet
  
deploy:
- provider: NuGet
  server: https://www.myget.org/F/quahu/api/v2
  api_key:
    secure: XW7HgRlmPz8/YHNSCAjAzBbYvgTx1dVSA+OU8AmuU6OamtFJnUr2CCAbHukPg0r7
  skip_symbols: true
  on:
    branch: master
    appveyor_repo_tag: false
- provider: NuGet
  api_key:
    secure: Y38g37rprY0qDdxvx4Ml8Q9Mja12lZCQ1MfEDv3b1he46KgogNFMMEKtLB1pPF1d
  on:
    appveyor_repo_tag: true